//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace KlioWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        
        public int StudentId { get; set; }
        [Required(ErrorMessage = "Field is required.")]
        public string StudentName { get; set; }

        [Required(ErrorMessage = "Field is required.")]
        public Nullable<int> StudentFees { get; set; }

        [Required(ErrorMessage = "Field is required.")]
        public string StudentCity { get; set; }

        [Required(ErrorMessage = "Field is required.")]
        public string StudentAddress { get; set; }

        [Required(ErrorMessage = "Field is required.")]
        public Nullable<System.DateTime> StudentDOJ { get; set; }
    }
}
